import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react';
import NavBar from '/components/NavBar/Navbar';
import SideNav from '/components/SideNav/SideNav';
import Footer from '/components/Footer/Footer';
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
    title: 'Royal Comission For Riyadh City',
    description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
                <link href="https://fonts.cdnfonts.com/css/gilroy-bold?styles=20876,20877,20878,20879,20880" rel="stylesheet" crossorigin="anonymous" referrerpolicy="no-referrer" />
                <link rel="icon" type="image/png" href="https://i.ibb.co/KhTB17d/Logo.png"/>
                <title>Royal Comission of Riyadh City</title>
            </head>
            <ChakraProvider>
                <body className='flex flex-row justify-start'>
                   <SideNav></SideNav> 
                    <div className="flex flex-col w-full background-color-gray-custom" >
                        <NavBar></NavBar>
                        <div className='background-color-gray-custom'>
                            {children}
                            <span id='loader' className="loader"></span>
                        </div>
                    </div>
                </body>
            </ChakraProvider>
            <Footer></Footer> 
        </html>
    )
}
